// Generated by Nicc's lc.py

#include <stdio.h>
#include <assert.h>

#define TRUE 1
#define FALSE 0

int defined_F(int k)
{
    if ((k == 0)) return 1;
    return k * defined_F(k - 1);
}

int defined_M(int a, int b)
{
    return a * b;
}

int defined_N(int a, int b)
{
    return !(a == b);
}

void prog(int n)
{
    printf("INPUT STATE\n");
    printf("n = %d\n", n);
    int f, k;

                              assert(TRUE);
                              assert(1 == defined_F(0));
    f = 1;                    assert(f == defined_F(0));
    k = 0;                    assert(f == defined_F(k));
    if (n == 0) {             assert(n == 0);
        f = 1;                assert(f == defined_F(k));
    } else {                  assert(defined_N(n,0));
        while (!(k == n)) {   assert((f == defined_F(k)) && defined_N(k,n));
                              assert(defined_M(f,(k + 1)) == defined_F(k + 1));
            k = k + 1;        assert(defined_M(f,k) == defined_F(k));
            f = f * k;        assert(f == defined_F(k));
        }                     assert(f == defined_F(k) && (k == n));
    }                         assert(f == defined_F(k));

    printf("OUTPUT STATE\n");
    printf("n = %d\n", n);
    printf("f = %d\n", f);
    printf("k = %d\n", k);
}

int main(void)
{
    printf("=== TEST CASE 1 ===\n");
    prog(0);

    printf("=== TEST CASE 2 ===\n");
    prog(1);

    printf("=== TEST CASE 3 ===\n");
    prog(3);

    printf("=== TEST CASE 4 ===\n");
    prog(5);

    return 0;
}
